version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo-test
    network_mode: host
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: test-grafana
    volumes:
      - mongodb-data:/data/db
      - ./init-mock/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    network_mode: host
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:
  mongodb-data: